config/routes.rb
Rails.application.routes.draw do
  root               'static_pages#home'

  get 'about'     => 'static_pages#about'
  get 'help'      => 'static_pages#help'

  get 'signup'    => 'users#new'
  post 'signup'   => 'users#create'

  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { email.downcase! }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrpyt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])

    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or users_path
    else
      flash[:danger] = 'Invalid email/password combination.'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = 'You have been successfully logged out.'
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    log_out if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      flash[:success] = 'You have successfully registered.'
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated successfully.'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.destroy(params[:id])
    flash[:success] = 'User successfully deleted.'
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = 'Please log in.'
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end

    def admin_user
      redirect_to root_path unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Symposium'

    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    else (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 350, responsive: true, centered: false)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"

    img_class = 'img-circle'
    img_class << ' img-responsive' if responsive
    img_class << ' img-centered' if centered

    image_tag(gravatar_url, alt: user.name, class: img_class)
  end
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Symposium', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Help', help_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Users', users_path %></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Account <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Profile', current_user %></li>
              <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_rails_defaults.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= render 'layouts/rails_defaults' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, class: "alert alert-#{message_type} alert-dismissable" do %>
          <a href="#" class="close", data-dismiss="alert" aria-label="close">&times;</a>
          <%= message %>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    The form contains <%= pluralize(@user.errors.count, "error") %>:
  </div>
  <ul class="list-group">
    <% @user.errors.full_messages.each do |msg| %>
      <li class="list-group-item list-group-item-warning"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>

<p>
  <a href="https://www.github.com/wencakisa/symposium" target="_blank">
    <strong>Symposium</strong>
  </a>
  is a blog-based web application, built with the <i>supermegacool</i> web framework -
  <a href="http://rubyonrails.org/" target="_blank">Ruby on Rails</a>.
</p>

<p>
  <a href="https://www.merriam-webster.com/dictionary/symposium" target="_blank">
    Wonder why <strong>Symposium?</strong>
  </a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>

<p>
  Need help? Open an issue in our
  <a href="https://github.com/wencakisa/symposium/issues" target="_blank">
    GitHub repository
  </a>.
</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome to Symposium!</h1>

  <% unless logged_in? %>
    <p>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary', role: 'button' %>
    </p>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, 'Confirmation' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit yield(:button_text), class: 'btn btn-success btn-lg center-block' %>
<% end %>

app/views/users/_pagination.html.erb
<div class="text-center">
  <%= will_paginate %>
</div>

app/views/users/_user.html.erb
<li class="list-group-item">
  <%= gravatar_for(user, size: 75, responsive: false) %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    |
    <%= link_to user, method: :delete, data: { confirm: 'Are you sure?' } do %>
      <span class="glyphicon glyphicon-trash"></span>
    <% end %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Update my profile') %>

<h1>Edit your user info</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="thumbnail">
      <a href="http://gravatar.com/emails", target="_blank" rel="noopener">
        <%= gravatar_for(@user, size: 180, centered: true) %>
      </a>
    </div>

    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>

<% if @users.empty? %>
  <h1>There are no users yet.</h1>
<% else %>
  <h1>All users: </h1>

  <%= render 'pagination' %>
  <ul class="list-group">
    <%= render @users %>
  </ul>
  <%= render 'pagination' %>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>

<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <div class="col-md-6 col-md-offset-3" id="profileInfo">
    <%= gravatar_for(@user, centered: true) %>
    <hr/>
    <p><strong>Name: </strong><%= @user.name %></p>
    <p><strong>Email: </strong><%= @user.email %></p>
    <% if current_user?(@user) %>
      <%= link_to 'Update profile info', edit_user_path(@user), class: 'btn btn-lg btn-info center-block' %>
    <% end %>
  </div>
</div>